version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: poposerver_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - poposerver_network

  postgres-test:
    image: postgres:15-alpine
    container_name: poposerver_postgres_test
    ports:
      - '8888:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - poposerver_network

  redis:
    image: redis:alpine
    container_name: poposerver_redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - poposerver_network

  redis-test:
    image: redis:alpine
    container_name: poposerver_redis_test
    ports:
      - '8889:6379' # 다른 포트 사용
    command: redis-server --appendonly no --requirepass ${REDIS_PASSWORD}
    tmpfs:
      - /data # 테스트용이므로 메모리에 저장 (빠름)
    networks:
      - poposerver_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: poposerver_redis_gui
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
    ports:
      - '8081:8081'
    depends_on:
      - redis
    networks:
      - poposerver_network

volumes:
  pg_data:
  redis_data:

networks:
  poposerver_network:
    driver: bridge
