version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: poposerver_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - poposerver_network

  postgres-test:
    image: postgres:15-alpine
    container_name: poposerver_postgres_test
    ports:
      - '8888:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - poposerver_network

volumes:
  pg_data:

networks:
  poposerver_network:
    driver: bridge
