version: "3.9"

services:
  db0:
    image: postgres:15
    container_name: db0
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_0_USERNAME}
      POSTGRES_PASSWORD: ${DB_0_PASSWORD}
      POSTGRES_DB: ${DB_0_NAME}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_0_PORT}:5432"
    networks:
      - poposerver

  account:
    container_name: account
    build:
      context: .
      dockerfile: apps/account/Dockerfile
    env_file:
      - .env
    ports:
      - "${SERVICE_ACCOUNT_PORT}:${SERVICE_ACCOUNT_PORT}"
    depends_on:
      - db0
    networks:
      - poposerver

networks:
  poposerver:
    driver: bridge
