version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - api
    networks:
      - poposerver

  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '${DB_PORT}:5432'
    networks:
      - poposerver

  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - .env.dev
    ports:
      - '${SERVICE_API_PORT}:${SERVICE_API_PORT}'
    volumes:
      - ./apps/api:/usr/src/app/api
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - poposerver

  ticket-job:
    container_name: ticket-job
    build:
      context: .
      dockerfile: apps/ticket-job/Dockerfile
    env_file:
      - .env.dev
    depends_on:
      - db
    ports:
      - '${JOB_TICKET_PORT}:${JOB_TICKET_PORT}'
    volumes:
      - ./apps/ticket-job:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - poposerver

  socket:
    container_name: socket
    build:
      context: .
      dockerfile: apps/socket/Dockerfile
    env_file:
      - .env.dev
    depends_on:
      - db
    ports:
      - '3001:3001'
    volumes:
      - ./apps/socket:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - poposerver

networks:
  poposerver:
    driver: bridge
