version: "3.9"

services:
  db0:
    image: postgres:15
    container_name: db0
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME_0}
      POSTGRES_PASSWORD: ${DB_PASSWORD_0}
      POSTGRES_DB: ${DB_NAME_0}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT_0}:5432"
    networks:
      - poposerver

networks:
  poposerver:
    driver: bridge
