version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - account
      - ingame
    networks:
      - poposerver

  db0:
    image: postgres:15
    container_name: db0
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_0_USERNAME}
      POSTGRES_PASSWORD: ${DB_0_PASSWORD}
      POSTGRES_DB: ${DB_0_NAME}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_0_PORT}:5432"
    networks:
      - poposerver

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - poposerver

  account:
    container_name: account
    build:
      context: .
      dockerfile: apps/account/Dockerfile
    env_file:
      - .env
    ports:
      - "${SERVICE_ACCOUNT_PORT}:${SERVICE_ACCOUNT_PORT}"
    depends_on:
      - db0
      - redis
    networks:
      - poposerver

  ingame:
    container_name: ingame
    build:
      context: .
      dockerfile: apps/ingame/Dockerfile
    env_file:
      - .env
    ports:
      - "${SERVICE_INGAME_PORT}:${SERVICE_INGAME_PORT}"
    depends_on:
      - db0
      - redis
    networks:
      - poposerver

  bag:
    container_name: bag
    build:
      context: .
      dockerfile: apps/bag/Dockerfile
    env_file:
      - .env
    ports:
      - "${SERVICE_BAG_PORT}:${SERVICE_BAG_PORT}"
    depends_on:
      - db0
      - redis
    networks:
      - poposerver

  ticket-cron:
    container_name: ticket-cron
    build:
      context: .
      dockerfile: apps/ticket-cron/Dockerfile
    env_file:
      - .env
    ports:
      - "${CRON_TICKET}:${CRON_TICKET}"
    depends_on:
      - db0
      - redis
    networks:
      - poposerver

networks:
  poposerver:
    driver: bridge
