export enum AppErrorCode {
  NETWORK_ERROR = 'NETWORK_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  DTO_INVALID = 'DTO_INVALID',
  SESSION_MISSING = 'SESSION_MISSING',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  ACCOUNT_ALREADY_EXIST = 'ACCOUNT_ALREADY_EXIST',
  FAILED_ACCOUNT = 'FAILED_ACCOUNT',
  ACCOUNT_ALREADY_DELETED = 'ACCOUNT_ALREADY_DELETED',
  EXCEED_REQUEST = 'EXCEED_REQUEST',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  NICKNAME_ALREADY_EXISTS = 'NICKNAME_ALREADY_EXISTS',
  NOT_IN_PLAZA = 'NOT_IN_PLAZA',
  ALREADY_IN_SAFARI = 'ALREADY_IN_SAFARI',
  NOT_IN_SAFARI = 'NOT_IN_SAFARI',
  SAFARI_ITEM_NOT_FOUND = 'SAFARI_ITEM_NOT_FOUND',
  SAFARI_ITEM_ALREADY_PICKED = 'SAFARI_ITEM_ALREADY_PICKED',
  SAFARI_WILD_NOT_FOUND = 'SAFARI_WILD_NOT_FOUND',
  SAFARI_WILD_ALREADY_CAUGHT = 'SAFARI_WILD_ALREADY_CAUGHT',
  SAFARI_WILD_ALREADY_FLED = 'SAFARI_WILD_ALREADY_FLED',
  SAFARI_BALL_NOT_FOUND = 'SAFARI_BALL_NOT_FOUND',
  POKEMON_NOT_FOUND = 'POKEMON_NOT_FOUND',
  EVOLUTION_NOT_AVAILABLE = 'EVOLUTION_NOT_AVAILABLE',
  EVOLUTION_COST_INVALID = 'EVOLUTION_COST_INVALID',
  EVOLUTION_COST_NOT_ENOUGH = 'EVOLUTION_COST_NOT_ENOUGH',
  MOVE_NOT_LEARNABLE = 'MOVE_NOT_LEARNABLE',
  MOVE_ITEM_NOT_FOUND = 'MOVE_ITEM_NOT_FOUND',
  MOVE_ALREADY_LEARNED = 'MOVE_ALREADY_LEARNED',
  POKEMON_IN_PARTY = 'POKEMON_IN_PARTY',
  ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
  ITEM_NOT_SELLABLE = 'ITEM_NOT_SELLABLE',
  ITEM_NOT_PURCHASABLE = 'ITEM_NOT_PURCHASABLE',
  ITEM_INSUFFICIENT_QUANTITY = 'ITEM_INSUFFICIENT_QUANTITY',
  INSUFFICIENT_MONEY = 'INSUFFICIENT_MONEY',
  PARTY_LIMIT_EXCEEDED = 'PARTY_LIMIT_EXCEEDED',
  INVALID_ARRANGEMENT = 'INVALID_ARRANGEMENT',
}

export enum AppErrorMessage {
  NETWORK_ERROR = 'Network error',
  INTERNAL_SERVER_ERROR = 'Interval Server Error',
  NOT_FOUND = 'Not found.',
  DTO_INVALID = 'Dto Invalidation Error.',
  SESSION_MISSING = 'Session is missing',
  SESSION_EXPIRED = 'Session is Expired',
  ACCOUNT_ALREADY_EXIST = 'Account already exist',
  FAILED_ACCOUNT = 'Account Failed',
  ACCOUNT_ALREADY_DELETED = 'Account already deleted',
  USER_NOT_FOUND = 'User not found',
  USER_ALREADY_EXISTS = 'User already exists',
  NICKNAME_ALREADY_EXISTS = 'Nickname already exists',
}

export interface AppErrorRes {
  success: false;
  error: {
    code: AppErrorCode;
    message: string | null;
    status: number;
  };
}
